### ISSUE TITLE
Login of different user fails when renew=true

### ISSUE THREAD

**Issue by bifyu** [apereo/cas#2262]
Login for subsequent different user fails after login of first user when renew=true.
Note: _**renew=true** is required to trigger this behavior._

- CAS server version
  - 5.0.2-SNAPSHOT (AuthN using LDAP, JSON service registry)
- Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
  - Tomcat 8.0.39, Java 1.8.0_112
- Steps to duplicate the problem
1. define registered service for testing purposes (JSON)
`{
  "name" : "Different_User_Test",
  "serviceId" : "^https://example\\.edu.*",
  "description" : "Stub registration to test different user problem",
  "id" : 20161223100000,
  "evaluationOrder" : 99999999,
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
}`
3. use a new private/incognito browser window for test service URL (the renew=true parameter is required)
`https://cas.example.edu/cas/login?renew=true&service=https%3A%2F%2Fexample%2Eedu`
4. authenticate as user1
5. reload test service URL in the same tab
`https://cas.example.edu/cas/login?renew=true&service=https%3A%2F%2Fexample%2Eedu`
6. authenticate as user2

This second time, after providing correct credentials for user2, CAS reports error for incorrect username or password.

- CAS debug logs
  - [CAS5-diff-users.log](https://gist.github.com/bifyu/126a90ada2b0dd62fa25d689a7669e1e#file-cas5-diff-users-log)

**Comment by mmoayyed** [comment]
Resolved in 5.0.2 SNAPSHOT

**Comment by bifyu** [comment]
Should I be seeing the fix in 5.0.2-SNAPSHOT? Still seeing the problem with build as of time of this comment. Presumably relevant log(?): ```ERROR [org.apereo.cas.web.flow.AuthenticationExceptionHandler] - <Unable to translate handler errors of the authentication exception org.apereo.cas.authentication.MixedPrincipalException: user1 != user2. Returning UNKNOWN by default...>```

**Comment by mmoayyed** [comment]
I am unable to duplicate this using the latest 5.0.2 SNAPSHOT. Please make sure you're running the latest snapshot and report back.

**Comment by bifyu** [comment]
confirmed fixed in latest published 5.0.2-SNAPSHOT
