### ISSUE TITLE
Issue running CAS: logging.properties not found

### ISSUE THREAD

**Issue by mhgs** [apereo/cas#2273]
I encounter a issue start CAS on a linux server. I am able to start CAS on my development machine but when rolling out CAS to a linux server (Pivotal tcServer) I encounter a issue. The logging.properties could not be found. The file does exist and is readable for anyone. Also the mentioned `/-Djava.util.logging.config.file=` is never set in my setup. 

I use the native profile setup and have a extra spring profile defined for the environment "-Dspring.profiles.active=native,acceptance". 

The bootstrap.properties contains 2 lines (see below):
`spring.profiles.active=native `
`spring.cloud.config.server.native.searchLocations=classpath:/`

I've got a application-acceptance.properties containing the following line regarding the logging:
`logging.config=classpath:/log4j2-accept.xml`

**CAS version:**

`CAS Version: 5.1.0-RC2-SNAPSHOT`
`CAS Build Date/Time: 2017-01-04T14:21:44Z`
`Spring Boot Version: 1.4.3.RELEASE`
`Apache Tomcat Version: Pivotal tc Runtime 3.0.3.RELEASE/8.0.20.B.RELEASE`
`---------------------------------------------`
`System Date/Time: 2017-01-04T15:37:05.276+01:00[Europe/Amsterdam]`
`System Temp Directory: /var/www/html/tcserver/pivotal-tc-server-standard-3.0.3.RELEASE/login_accept/temp`
`---------------------------------------------`
`Java Home: /var/www/html/java/jdk1.8.0_45/jre`
`Java Vendor: Oracle Corporation`
`Java Version: 1.8.0_45`
`JCE Installed: no`
`---------------------------------------------`
`OS Architecture: amd64`
`OS Name: Linux`
`OS Version: 3.10.0-229.4.2.el7.x86_64`

**Stacktrace:**

```
> 2017-01-04 15:37:29,513 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.loggingConfigController': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: ServletContext resource [/-Djava.util.logging.config.file=/var/www/html/tcserver/pivotal-tc-server-standard-3.0.3.RELEASE/login_accept/conf/logging.properties] cannot be resolved to URL because it does not exist>
2017-01-04 15:37:29,522 WARN [org.apereo.cas.services.ServiceRegistryConfigWatcher] - <Directory key is no longer valid. Quitting watcher service>
2017-01-04 15:37:29,574 ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.loggingConfigController': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: ServletContext resource [/-Djava.util.logging.config.file=/var/www/html/tcserver/pivotal-tc-server-standard-3.0.3.RELEASE/login_accept/conf/logging.properties] cannot be resolved to URL because it does not exist
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1581) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$2.getObject(AbstractBeanFactory.java:345) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:359) ~[spring-cloud-context-1.1.6.RELEASE.jar:1.1.6.RELEASE]
        at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:176) ~[spring-cloud-context-1.1.6.RELEASE.jar:1.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.cloud.context.scope.refresh.RefreshScope.start(RefreshScope.java:121) ~[spring-cloud-context-1.1.6.RELEASE.jar:1.1.6.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169) ~[spring-web-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5151) ~[catalina.jar:8.0.20.B]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.0.20.B]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) ~[catalina.jar:8.0.20.B]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) ~[catalina.jar:8.0.20.B]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) ~[catalina.jar:8.0.20.B]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:917) ~[catalina.jar:8.0.20.B]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1701) ~[catalina.jar:8.0.20.B]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: ServletContext resource [/-Djava.util.logging.config.file=/var/www/html/tcserver/pivotal-tc-server-standard-3.0.3.RELEASE/login_accept/conf/logging.properties] cannot be resolved to URL because it does not exist
        at com.google.common.base.Throwables.propagate(Throwables.java:240) ~[guava-20.0.jar:?]
        at org.apereo.cas.web.report.LoggingConfigController.initialize(LoggingConfigController.java:86) ~[cas-server-support-reports-5.1.0-RC2-SNAPSHOT.jar:5.1.0-RC2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        ... 45 more
Caused by: java.io.FileNotFoundException: ServletContext resource [/-Djava.util.logging.config.file=/var/www/html/tcserver/pivotal-tc-server-standard-3.0.3.RELEASE/login_accept/conf/logging.properties] cannot be resolved to URL because it does not exist
        at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:156) ~[spring-web-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:99) ~[spring-core-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.apereo.cas.web.report.LoggingConfigController.initialize(LoggingConfigController.java:82) ~[cas-server-support-reports-5.1.0-RC2-SNAPSHOT.jar:5.1.0-RC2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        ... 45 more
Jan 04, 2017 3:37:29 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 34496 ms
```

**Comment by mmoayyed** [comment]
Sounds like an issue for Pivotal tcServer folks or Spring Boot folks to review with you.

**Comment by mmoayyed** [comment]
What's for certain is that the logging configuraion isnt picked by Spring Boot for some reason. It likely has to do with classpath prefix, which doesn't make a whole lot of sense in your config. Why do that when you already have a logging config file on the classpath?

**Comment by mhgs** [comment]
Are you sure it has something to do with spring boot? When inspecting the stack trace I see that something is going wrong when cas.report.loggingConfigController is initialized:

` at org.apereo.cas.web.report.LoggingConfigController.initialize(LoggingConfigController.java:82) ~[cas-server-support-reports-5.1.0-RC2-SNAPSHOT.jar:5.1.0-RC2-SNAPSHOT]`

 
 
Btw: the reason I use the class path settings, is that I want to use multiple configs for different spring profiles. The war file is build and deployed using a automated build and deploy tool.

**Comment by mmoayyed** [comment]
You may be onto something. Let me run through this once.

**Comment by mmoayyed** [comment]
This (The weirdness with the logging controller, etc) should be fixed in the latest snapshot. Please try again and report back.

**Comment by mhgs** [comment]
Just tried with the new build, still experiencing exactly the same issue now on another line:

`at org.apereo.cas.web.report.LoggingConfigController.initialize(LoggingConfigController.java:94)`

**Comment by mmoayyed** [comment]
Can you upload an overlay that demonstrates this issue to the issues project?

**Comment by mhgs** [comment]
Just posted the file (https://drive.google.com/file/d/0B4tKeymCL1IJN2ZSUElVeUdHcVU/view?usp=sharing) I did not cleanup anything in the project, only removed passwords etc.

**Comment by mhgs** [comment]
Already tried that, same result. Tried to use classpath: settings (with/without a slash), also tried configuring it with absolute paths using the file://.

**Comment by lyhngug** [comment]
I have the same problem only in windows  tomcat8.x. with cas-5.10-rc2 too.In Linux it runs without any exceptions.


[catalina.2017-01-05.txt](https://github.com/apereo/cas/files/687513/catalina.2017-01-05.txt)

**Comment by mhgs** [comment]
Judging by the log @lyhngug attached the issue is not restricted to my current setup. I also upgraded my tc instance to the latest versions of pivotal tc, tomcat and JDK. See attached logs and my setup. I still experiencing this issue.

[logs.txt](https://github.com/apereo/cas/files/687580/logs.txt)

**Comment by mmoayyed** [comment]
Short of it is, somehow somewhere in your configuration `logging.config` is set to something that closely mimics `/var/www/html/tcserver/pivotal-tc-server-standard-3.0.3.RELEASE/login_accept/conf/logging.properties`. When CAS attempts to find the value associated with `logging.config`, it gets that file instead, and it obviously fails to load it. There isn't anything in CAS that looks for logging.properties, etc. So, look in your tomcat environment and find where that setting is set, either via a script, a system property, etc. You may also want to run the embedded container version to compare results.

**Comment by mmoayyed** [comment]
I am also going to throw this out there, that I am almost sure this is related to a path parsing issue somewhere.

**Comment by mhgs** [comment]
I was digging further into the Catalina.sh file (of the Tomcat version I am using). I discovered that the logging path we're seeing has something to do with the lines in the Catalina.sh below:

`# Set juli LogManager config file if it is present and an override has not been issued`
`if [ -z "$LOGGING_CONFIG" ]; then`
`  if [ -r "$CATALINA_BASE"/conf/logging.properties ]; then`
`    LOGGING_CONFIG="-Djava.util.logging.config.file=$CATALINA_BASE/conf/logging.properties"`
`  else`
`    # Bugzilla 45585`
`    LOGGING_CONFIG="-Dnop"`
`  fi`
`fi`

`if [ -z "$LOGGING_MANAGER" ]; then`
`  LOGGING_MANAGER="-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager"`
`fi`

I'm only not sure why these lines are there. Also good to mention, I search my entire tc instance including the deployed war file, but the logging properties are not set anywhere. That's why I turned to the tomcat files and found where the path is coming from.

**Comment by mmoayyed** [comment]
Good info. Some additional resources to study: http://stackoverflow.com/questions/25491064/spring-boot-logging-configuration-when-deployed-as-war (First answer). 

When happens when you comment out that block from catalina.sh file? Does the error go away for the time being? It looks like `$LOGGING_CONFIG` is read by Boot's environment bootstrapping and then substituted for `logging.config`?

**Comment by mmoayyed** [comment]
Also, are you able to make a few code mods? Specifically, change this line https://github.com/apereo/cas/blob/master/support/cas-server-support-reports/src/main/java/org/apereo/cas/web/report/LoggingConfigController.java#L91

```
final String logFile = environment.getProperty("logging.config");
```

**Comment by lyhngug** [comment]
My problem is solved after updating the sources .thanks a lot.

**Comment by mmoayyed** [comment]
Excellent. The mod will be included in later snapshots.

**Comment by mhgs** [comment]
I just tested the above mentioned solutions, but still experiencing the same issue. Still the default, by tomcat added, value is used and causing this error. I alter the code to get a property like `logging.config.testing` and it works instantly. 

As we already concluded earlier, it has something to do with how spring boot is parsing the LOGGING_CONFIG to the logging.config property. I also investigated if this was a timing issue, for example if the property `logging.config` was not properly set for some reason if the value was read using `@Value` or within the `@PostConstruct`. but also later on if the application was started correctly, the value still returns a incorrect value. For now I think we can close the issue over here and hope spring boot is fixing this issue for certain server configurations. 

My workaround is not pretty, but I defined a custom property and created my own instance of the loggingController to digest this custom property is this custom property is defined, otherwise, the default property is read.

**Comment by mmoayyed** [comment]
You may want to also raise this issue to the boot folks either as an issue or a post on stackoverflow.

**Comment by MTL0** [comment]
@mhgs You may get it resolved by flowing this post . See the answer of  **Yauheni Sidarenka** [ getting Logging config file location '-Djava.util.logging.config.file' not found error](https://groups.google.com/a/apereo.org/forum/#!searchin/cas-user/logging/cas-user/kgBBtZ5AM1c/PGS06xWsBgAJ) .
