### ISSUE TITLE
MongoDb ticket cleanup

### ISSUE THREAD

**Issue by benht** [apereo/cas#2748]
This line in MongoDbTicketRegistry seems a bit confused:

collection.createIndex(new BasicDBObject(TicketHolder.FIELD_NAME_EXPIRE_AT, 1),
                new BasicDBObject("expireAfterSeconds", 0));

It creates an index to expire records in the collection 0 seconds after the date in the expireAt_1 field (that's the TicketHolder.FIELD_NAME_EXPIRE_AT part).

The problems are :
* (assuming I'm reading the index information right) expireAt_1 isn't the field name, it's expireAt
* 0 isn't a valid value for the expireAfterSeconds index (see https://docs.mongodb.com/manual/tutorial/expire-data/)
* expireAt gets the TTL value, not a date

I'm up for fixing it, but not sure how best to do so.  It seems like the current expireAt field should be renamed and set to the ticket's "lastTimeUsed" field.  Perhaps a better idea would be to use an expireAt index/field and set that to be a date (that would then need updating when the ticket was used).

**Comment by mmoayyed** [comment]
Please use the issue template to report an issue. 

This should b resolved and fixed in the latest RC1 release.

**Comment by benht** [comment]
Sorry I missed things from the issue template before.

I've just been looking at the latest code from the master branch and I think this issue is still present in MongoDbTicketRegistry.createTicketCollection(ticket).  

The index that it applies (expireAfterSeconds) needs to be applied "on a field whose value is either a date or an array that contains date values" (quoting from the MongoDb docs).  So when it's applied to the expireAt field which gets set to the TTL (in seconds) it'll never do anything.  I've confirmed it works if you set expireAt to a date.

The question I have (and reason why there's no pull request yet) is because I'm not sure how picky to be about which date to use.  The easiest way would be to assume CAS and Mongo both have the same date and use that + TTL in the TicketHolder object.  If we don't want to assume they're in sync then we'd have to get and maintain an offset etc.  Ideally we'd say to Mongo - use NOW() + TTL (will look into that).

- [5.11 - 5.2RC1] CAS server version
- [Tomcat 8.0.26, Windows, Mongo 3.2] Container/environment type/version
- Steps to duplicate the problem 

Set cas.ticket.tgt.hardTimeout.timeToKillInSeconds=20 so that tickets won't live long.  MongoDb runs its clear-up process every 60 seconds.

Start CAS, log in, look at tickets in MongoDb, wait a couple of minutes => tickets don't get removed

- [] Stacktraces and CAS DEBUG logs where appropriate.
n/a
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/ or attached to the issue.
n/a

**Comment by mmoayyed** [comment]
Outstanding; Thanks for the pull request. (Remember that you dont need to create issues. The PR is the issue and that's usually where conversations should happen anyway). I think the solution you have in the PR is perfectly fine for the time being and we can improve later if time sync issues surface up. Thanks for tracking this one down again.

**Comment by benht** [comment]
Yey - 1st pull request!
"fine for the time being" - I agree.  I'll look out for issues when we actually deploy this.
Thanks!

**Comment by mmoayyed** [comment]
Thank you. I didnt realize you were a first-timer. Outstanding job! Are you on twitter? Wanted to give you a shout out.

**Comment by benht** [comment]
Thanks :) but not on Twitter.

**Comment by mmoayyed** [comment]
All the same: https://twitter.com/misagh84/status/882678493187911680
